name: videostreaming
description: A new Flutter project.



publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  youtube_player_iframe: ^2.2.2
  cached_network_image: ^3.2.0
  loader_skeleton: ^0.0.4
  easy_splash_screen: ^1.0.3
  
  
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  

flutter:
  uses-material-design: true

  assets:
    - Assets/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
